### ISSUE TITLE
Deviations in calculated water depth between tool and Lizard

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedidepth#2] opened 2020-10-08 14:49 UTC
after installing the tool in qgis I have processed a result from the city of groningen (selwerd) and compared it with the data in Lizard. I have made the tiffs available here:
K:\J_vSchrojenstein\3Di\localwaterdepth

Some screenshots:
Lizard:
![image](https://user-images.githubusercontent.com/1453159/95474789-d55eeb00-0985-11eb-95a5-209d6fb6dd1e.png)
QGIS:
![image](https://user-images.githubusercontent.com/1453159/95474844-e576ca80-0985-11eb-9eff-c47e19dd41aa.png)

Lizard:
![image](https://user-images.githubusercontent.com/1453159/95474945-fd4e4e80-0985-11eb-9424-d7dd1100466f.png)
QGIS:
![image](https://user-images.githubusercontent.com/1453159/95474966-050df300-0986-11eb-9c10-90f7f95af490.png)

these are just a few examples, there is way more difference than this, above screenshots are to give an idea

**Comment by arjanverkerk** [comment] 2020-10-09 08:18
Hi, nice work. I'm curious to see if this has to do with the different nodata strategy or something else.

What were your settings (interpolation, timestep)?
Can you park dem, gridadmin and 3di results in said location, too?

**Comment by Jonasvsl** [comment] 2020-10-09 09:01
done

**Comment by arjanverkerk** [comment] 2020-10-14 15:43
@Jonasvsl What timestep did you use for the local calculation? My result seems different than the default.
@jpprins1 I thought I followed your advice about interpolating and nodata - but then you should regularly see those missing depths in the livesite, too. Have you?

**Comment by jpprins1** [comment] 2020-10-14 17:05
I cannot recall seeing those missing parts of channels like above. But I've also never compared Lizard and 3Di waterdepths images/tiffs like this.

The interpolation & handling of nodata for the waterdepth images is the same way as for the 'old' livesite, so probably somebody should have noticed it if it's that different?

**Comment by Jonasvsl** [comment] 2020-10-15 06:26
@arjanverkerk I used the scenario: Groningen selwerd #81 73 mm1u . You should be able to see the timestep in there right?
Although I would expect deviations this seems like a lot. Do you also need the calculation grid?

**Comment by arjanverkerk** [comment] 2020-10-16 08:17
I derived the timestep from the timestamp in your download: step 12 (one hour into the sim). And indeed, the differences are explained by the method. In my screenshots it's clear that the artifacts found by @Jonasvsl are caused by the waterlevel (crater-like objects) going to -9999 for a specific node. This is how I understood the method as described by @jpprins1.

![void1](https://user-images.githubusercontent.com/751999/96232710-575b9f00-0f98-11eb-97d7-70d6acf6b843.png)
![void2](https://user-images.githubusercontent.com/751999/96232716-575b9f00-0f98-11eb-9900-37f0db047bc1.png)

**Comment by Jonasvsl** [comment] 2020-10-16 09:10
@arjanverkerk how does Lizard postprocessing handle these -9999 ?

In the live site (Selwerd model revision 81, 73 mm for 1 hour I get this:

![image](https://user-images.githubusercontent.com/1453159/96239597-34cd8400-0fa0-11eb-91ce-1043ea5f817a.png)

**Comment by Jonasvsl** [comment] 2020-10-16 09:11
![image](https://user-images.githubusercontent.com/1453159/96239695-5169bc00-0fa0-11eb-8548-0696728a5754.png)

**Comment by arjanverkerk** [comment] 2020-10-16 11:06
Interesting. In the first live site screenshot we can see the dip in the same place, but it is definitely not going down as fast as in the qgis / threedidepth result. It would be interesting to see the values at the nodes in this particular running simulation, but I have no idea how doable that is, or who to ask.

> @arjanverkerk how does Lizard postprocessing handle these -9999 ?

Lizard stores for each pixel the weights of each of the three nodes that form the triangle in which the pixel is situated. The waterlevel at a pixel and for a certain timestep is then evaluated as the weighted average of the values at the nodes that are _not_ "no data" (-9999). But if more than 50% of the total weight points to nodes with a "no data" value, the result is no data.

**Comment by Jonasvsl** [comment] 2020-10-16 12:03
It's darker blue so I interpreted it as deeper water, so the inverse of a dip. It is incorrect though, the water level on that location is level.
@jpprins1 can you give insight on how the -9999 case is handled into the live site?
@arjanverkerk: how difficult is it to implement the lizard way of handling the -9999 case?

**Comment by arjanverkerk** [comment] 2020-10-16 12:14
My bad, darker is deeper indeed, good to know that the level is flat. So may guess would be that the livesite gets the minimum bathy for the cell as input for the node, whereas in the netcdf this is converted to 'no data' aka -9999. But that assumption maybe completely wrong ;-)...

The lizard way can be done in a roughly a day or so.

**Comment by Jonasvsl** [comment] 2020-10-19 07:15
@jpprins1 
looking at this I feel like we should implement the lizard postprocessing algorithm. What do you think?

**Comment by jpprins1** [comment] 2020-10-19 12:16
@Jonasvsl: Yes, this would ensure the results in QGIS are the same as in Lizard. 
@arjanverkerk: Sorry for the extra work, but at least know we no for sure that the difference between one and the other method is too large. 

**Remaining the following questions/points:**
- Are we happy enough with the current livesite interpolation? (and if not, can we do something about it without loosing to much performance)
- I just heared that Eva also has generated some options for interpolation, which might even be better?
- Related: Is there any way we can maybe do a quantitative test/measurement of the accurancy of interpolation method X?

**Comment by Jonasvsl** [comment] 2020-10-19 12:29
@jpprins1 the current livesite interpolation is doing its job at the moment. Maybe the triangles in channels, but except for my comment last week I have never heard anyone about it

@arjanverkerk can you adjust the waterdepth script to use the lizard interpolation?
Users will be more inclined to compare it with the lizard version than the local version I think anyway
Ask Lex to add this ticket / story point to either this sprint or the next?

**Comment by arjanverkerk** [comment] 2020-10-20 13:17
We followed the plan to implement interpolation in the same way as the livesite. I checked this (github)-issue is actually the expected behavior according to my understanding of that implementation. It therefore remains to be investigated why the livesite method does not show these artifacts. That may reveal an easy modification to the current method which brings threedidepth and livesite results in accordance. Hopefully @jpprins1 or one of his team members can shine more light on this.

@joeriverheijden @Jonasvsl @lexvand I feel we should not yet switch to the lizard interpolation, before we understand the above situation.

**Comment by Jonasvsl** [comment] 2020-10-20 13:19
@arjanverkerk I do understand your sentiment, but in my view there should be not much difference between the live site and the lizard to begin with. Since the extra work to adjust it to Lizard is 1 day I'm not sure whether we should spent time in investigating this

**Comment by arjanverkerk** [comment] 2020-11-11 09:00
Closing because this is not a bug. Created feature request #3.

**Closed by arjanverkerk** 2020-11-11 09:00 UTC
Labels: Sprint disruption, bug
